### ISSUE TITLE
Individual spawnpoints beside flag

### ISSUE THREAD

**Issue by The0zzy** [RoflKartoffelDE/bf2042-portal-experience-ctf-tdm#1]
Currently there is a random offset on the flag-base where players spawn.
It turned out that this is still too close to the flag and also has potential for spawncamping.

Add at least two individual spawnpoints and apply the random offset there.

**Comment by The0zzy** [comment]
started implementation

**Comment by The0zzy** [comment]
Logic is there, but specific spawnpoints need to be added in the code

**Comment by Matavatar** [comment]
Spawns fucked up on Valparaiso.

Improve spawn logic (remove random distance from spawn point?)

**Comment by The0zzy** [comment]
removed randomization on spawnpoints, but there are still issues on valparaiso

**Comment by The0zzy** [comment]
spawnpoints basically work and are implemented for current map rotation
