### ISSUE TITLE
Play voiceover for each team when flag is picked up, captured, dropped

### ISSUE THREAD

**Issue by Matavatar** [RoflKartoffelDE/bf2042-portal-experience-ctf-tdm#5]
Ennemy Flag related
Flag taken : **Friendly leading** ?
Ennemy Flag captured :  **Objective Taken**
Flag dropped : **Objective lost**

Ally Flag related
Flag captured by ennemy : **Objective under attack**
Ally Flag Taken : **Ennemy Leading**

**Comment by Matavatar** [comment]
Removed Flag captured by ennemy voice over as not working for now.

Need to find a fix.

**Comment by The0zzy** [comment]
sounds implemented and needed a wait(0.1) between sounds for different teams in order to work correctly
